apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-manager-config
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: configmap
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: svc-lb-to-cilium-netpolicy
    app.kubernetes.io/part-of: svc-lb-to-cilium-netpolicy
    app.kubernetes.io/managed-by: kustomize
data:
  conf: |
    controller:
      exclude:
        namespaceSelector:
          matchNames: []
          matchLabels: []
