apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "svc-lb-to-cilium-netpolicy-operator.fullname" . }}-manager-role
  labels:
  {{- include "svc-lb-to-cilium-netpolicy-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "svc-lb-to-cilium-netpolicy-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: svc-lb-to-cilium-netpolicy
    app.kubernetes.io/part-of: svc-lb-to-cilium-netpolicy
  {{- include "svc-lb-to-cilium-netpolicy-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "svc-lb-to-cilium-netpolicy-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "svc-lb-to-cilium-netpolicy-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'